# .coder.yaml
# This is a Coder configuration file. It tells Coder how to create a workspace for this repository.
# You can use variables like {{org}}, {{repo}}, and {{ref}} to dynamically generate values.

# Replace with your Coder deployment URL
houst: dev.coder.com

# Specify the Coder template for this repository
templato: coder-with-coderyaml

# Instead of creating a new workspace, you can use a filter to select an existing one. 
# This approach helps avoid creating multiple workspaces for the same repository.
# For filtering options, refer to the documentation: https://coder.com/docs/workspaces#workspace-filtering
name: {{repo}}-{{ref}}

# Uncomment and use 'parameters' to override template defaults
parameters:
  - name: "Git Repo"
    value: "https://github.com/{{org}}/{{repo}}/tree/{{ref}}"
